# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jySVMore10N9eaQ6K9CuZ5Fl8__fYWMO
"""

import math
import random as rd
import numpy as np
import matplotlib.pyplot as plt


print("There are 52 complete weeks in a leap year")
a = 52
b = 7
c = a*b
d = 366 - c
e = d/b

print("So they will be 52 saturdays for sure")
print("Remaining days = 366 - 364 = 2 ")
print("So the probability of occurence of a  53rd Saturday is {0}".format(e))
cases = [0]
theoretical_results = [2/7]
simulated_results = [e]
x = np.arange(len(cases))
plt.bar(x + 0.00, theoretical_results, color = 'blue', width = 0.30, label = 'Theoretical results')
plt.bar(x + 0.30, simulated_results, color = 'green', width = 0.30, label = 'Simulated results')
plt.ylabel('Probability of 53 Saturdays in leap year')
plt.xlabel('Theoretical vs Simulated')

plt.legend()
plt.show()

