# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TKoGza2gT9Mq7lMtc4E3IQPjal0V3diK
"""

import random
import numpy as np
import matplotlib.pyplot as plt
import pylab


print("There are 52 complete weeks in a leap year")
a = 52
b = 7
c = a*b
d = 366 - c
e = d/b

print("So there will be 52 saturdays for sure")
print("Remaining days = 366 - 364 = 2 ")
print("So the probability of occurence of a  53rd Saturday is {0}".format(e))

Pair_of_days= ["Monday-Tuesday","Tuesday-Wednesday","Wednesday-Thursday","Thursday-Friday","Friday-Saturday","Saturday-Sunday","Sunday-Monday"]

test_cases = 10000
count = 0

for i in range(test_cases):
  index = random.randint(0,6)
  if Pair_of_days[index] == 'Saturday-Sunday':
    count = count + 1
  if Pair_of_days[index] == 'Friday-Saturday':
    count = count + 1
  i = i + 1
print(count)

probsim = count/test_cases
probtheo = e

cases = [0]
theoretical_results = [probtheo]
simulated_results = [probsim]
x = np.arange(len(cases))
plt.bar(x + 0.00, theoretical_results, color = 'blue', width = 0.30, label = 'Theoretical results')
plt.bar(x + 0.30, simulated_results, color = 'green', width = 0.30, label = 'Simulated results')
plt.ylabel('Probability of 53 Saturdays in leap year')
plt.xlabel('Theoretical vs Simulated')

plt.legend()
plt.show()