# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19SvnusnzSHQ9oZbeusVWHDVGFVrhizhQ
"""

import matplotlib.pyplot as plt
import pylab

#plotting the probability

P = [0.25,0.25,0.4,0.1]


X = [0,1,2,3]

 

# set the x axis and y axis limits

pylab.xlim([-1,4])

pylab.ylim([0,1])


plt.xlabel('X')

plt.ylabel('Pr(X)')

markerline, stemlines, baseline = plt.stem(X, P, '-')

plt.show()