# -*- coding: utf-8 -*-
"""Assignment 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKHm8YU8PjbdXyHvkzy-ROAqhF64rgMm
"""

import numpy as np
import matplotlib.pyplot as plt

a = 0.2
b = a
c = 1
x = np.linspace(0, 35, 500, endpoint = False)
y = (a * np.exp(-b*x))

plt.plot(x, y, '-r', label=r'$y = 1/5e^{-x/5}$')

axes = plt.gca()
axes.set_xlim([x.min(), x.max()])
axes.set_ylim([y.min(), y.max()])

plt.xlabel('x')
plt.ylabel('f(x)')
plt.title('Probability')
plt.legend(loc='upper left')

plt.show()

a = 0.2
b = a
c = 1
x = np.linspace(0, 35, 500, endpoint = False)
y = (c - np.exp(-b*x))

plt.plot(x, y, '-r', label=r'$y = 1 - e^{-x/5}$')

axes = plt.gca()
axes.set_xlim([x.min(), x.max()])
axes.set_ylim([y.min(), y.max()])

plt.xlabel('X = x')
plt.ylabel('F(x)')
plt.title('CDF of X')
plt.legend(loc='upper left')

plt.show()