# -*- coding: utf-8 -*-
"""Challenging problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jOTEVubp7zpBZph1SWcQtyE0iL1b5fVO
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon
pts = np.array([[0.25,0.25], [0.25,0.5], [0.5,0.25]])
p = Polygon(pts, closed=False)
ax = plt.gca()
ax.add_patch(p)
ax.set_xlim(0,0.75)
ax.set_ylim(0,0.75)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon
pts = np.array([[0,0], [0,1], [1,0]])
p = Polygon(pts, closed=False)
ax = plt.gca()
ax.add_patch(p)
ax.set_xlim(-0.5,1.5)
ax.set_ylim(-0.5,1.5)
plt.show()